name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # --- Показ только языков ---
          SHOW_LANGUAGE: 'True'

          # --- Отключаем всё лишнее ---
          SHOW_SHORT_INFO: 'False'
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_LINES_OF_CODE: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_COMMIT: 'False'
          SHOW_LOC_CHART: 'False'
